site_name: Docs Projeto de Mestrado
site_url: https://matheus1714.github.io/msc-proj/
theme:
  name: material
  palette:
  - scheme: slate
    primary: indigo
    accent: amber
    toggle:
      icon: material/weather-sunny
      name: Mudar para tema claro
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/weather-night
      name: Mudar para tema escuro
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
nav:
- Início: index.md
- experiment_directories_guide: experiment_directories_guide.md
- experiment_flow_diagram: experiment_flow_diagram.md
- experiment_workflow_structure: experiment_workflow_structure.md
- glove_download_guide: glove_download_guide.md
- Outros:
  - Outros: others/index.md
  - Cronograma: others/schedule.md
- Relatórios:
  - Relatórios: reports/index.md
  - Status:
    - Status Report - 29/06/2025: reports/status/status_report_2025_06_29.md
- RFCs:
  - RFCs: rfcs/index.md
  - Files:
    - RFC 0001 - Expansão dos Experimentos: rfcs/files/0001_experiments.md
    - 0002_hyperparams_sensibility: rfcs/files/0002_hyperparams_sensibility.md
- Study:
  - Técnicas de Classificação de Textos: study/0001_text_classification_techniques.md
- system_metrics_guide: system_metrics_guide.md
