site_name: RFCs do Projeto de Mestrado
theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Mudar para tema claro
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Mudar para tema escuro
docs_dir: rfcs
nav:
  - In√≠cio: 0001-primeira-rfc.md
  - Segunda RFC: 0002-segunda-rfc.md
