site_name: Docs Projeto de Mestrado
site_url: https://matheus1714.github.io/msc-proj/
theme:
  name: material
  palette:
  - scheme: slate
    primary: indigo
    accent: amber
    toggle:
      icon: material/weather-sunny
      name: Mudar para tema claro
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/weather-night
      name: Mudar para tema escuro
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences
nav:
- Início: index.md
- Outros:
  - Outros: others/index.md
  - Cronograma: others/schedule.md
- Relatórios:
  - Relatórios: reports/index.md
  - Status:
    - Relatório de Status - 29/06/2025: reports/status/status_report_2025_06_29.md
- RFCs:
  - RFCs: rfcs/index.md
  - Files:
    - 0001_experiments: rfcs/files/0001_experiments.md
